images/cluster-samples-operator/Dockerfile
samples-operator.spec

Some of this is invariably placeholder level correctness that will need to be tweaked as work progresses.

prep repo for distgit conventions

---

pkg/apis/samplesoperator/v1alpha1/types.go
pkg/stub/handler.go
pkg/stub/handler_test.go

@openshift/sig-developer-experience fyi/ptal
a collection of changes based on ideas of mine or discussions with @bparees on #aos-devexp

Group skip dir name

---

pkg/stub/handler.go
pkg/stub/handler_test.go

fix configmap creation; add bad post create cfg change test cases

---

tmp/build/assets/operator/ocp-ppc64le/ruby/imagestreams/ruby-rhel7.json
tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-ephemeral.json
tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-persistent.json
tmp/build/assets/operator/ocp-x86_64/mysql/templates/mysql-ephemeral.json
tmp/build/assets/operator/ocp-x86_64/mysql/templates/mysql-persistent.json
tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-ephemeral.json
tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-persistent.json
tmp/build/assets/operator/okd-x86_64/mysql/templates/mysql-ephemeral.json
tmp/build/assets/operator/okd-x86_64/mysql/templates/mysql-persistent.json

bump openshift/library assets

---

pkg/apis/samplesoperator/v1alpha1/types.go
pkg/stub/handler.go
pkg/stub/handler_test.go

@openshift/sig-developer-experience

add finalizer processing to ensure we see delete events

---

pkg/stub/handler.go
pkg/stub/handler_test.go

Fixes https://github.com/openshift/cluster-samples-operator/issues/24

check for credential before process rhel install with default registry

---

Makefile
pkg/apis/samplesoperator/v1alpha1/types.go
pkg/operatorstatus/operatorstatus.go
pkg/stub/handler.go

minor cluster operator fixes

---

pkg/apis/samplesoperator/v1alpha1/types.go
pkg/stub/handler.go
pkg/stub/handler_test.go

move sdk/samplesresource updates up to top of stack (allow grouping of changes);
genericize retry on api interactions;
move config map creation to startup

add managementstate;

---

pkg/stub/handler.go

https://bugzilla.redhat.com/show_bug.cgi?id=1653557

Fix typo "ppc64l3"

---

pkg/stub/handler.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1651909

clean up need cred error message

---

pkg/apis/samplesoperator/v1alpha1/types.go
pkg/stub/handler.go
pkg/stub/handler_test.go
test/e2e/cluster_samples_operator_test.go

Of course this is not the complete set of e2e's to do this sprint, but I uncovered enough code fix of relevance that I decided to break things up.
So here is the initial set

add e2e tests (along with fixes as a result)

---

cmd/cluster-samples-operator/main.go

add verbose logging config option to operator binary

---

pkg/apis/samplesoperator/v1alpha1/types.go
pkg/stub/handler.go
pkg/stub/handler_test.go

remove configmap and move its contents into SamplesResource.Status

---

Dockerfile
Dockerfile.rhel7
Makefile
pkg/apis/samplesoperator/v1alpha1/types.go
pkg/operatorstatus/operatorstatus.go

add git based version information a la openshift/origin

---

pkg/stub/handler.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1659351

add message in cfg valid condition if override unsupported mgmt state

---

deploy/00-crd.yaml
deploy/03-rbac.yaml
pkg/apis/samples/v1/types.go
pkg/operatorstatus/operatorstatus.go
pkg/stub/handler.go
pkg/stub/handler_test.go

this has commit from https://github.com/openshift/cluster-samples-operator/pull/76, which is still fighting aws flakes while on the merge queue
pls review https://github.com/openshift/cluster-samples-operator/pull/77/commits/7543e7d5085b07e8cbf60e47c512b9342656cdc9
will rebase, etc. as needed

Prevent usr upd status

---

deploy/05-operator.yaml

set cpu requests per new tech direction

---

README.md
pkg/apis/samples/v1/types.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/handler_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1662258

complete condition naming cleanup

---

pkg/apis/samples/v1/types.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1670280

do not require credentials if mgmt state removed/unmanaged

---

pkg/stub/config.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1670279

normal arch array to string in cannot change arch warning msg

---

manifests/08-kube-system-rbac.yaml
pkg/stub/handler.go
pkg/stub/secrets.go

copy pull images secret form kube-system by default

---

README.md
manifests/05-kube-system-rbac.yaml
pkg/operator/controller.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/handler_test.go
pkg/stub/secrets.go
test/e2e/cluster_samples_operator_test.go

Kube system cleanup

---

README.md
pkg/apis/samples/v1/types.go

change operator ID from 'instance' to 'cluster'

---

pkg/stub/interfaces.go

@smarterclayton fyi / ptal if you have bandwidth

use pumped up rate limiter, shave 30 seconds from startup creates

---

OWNERS

Add adambkaplan as owner

---

manifests/06-operator.yaml

/hold
will reword commit once bugzilla comes in
but getting testing started in the interim

BUG 1685228: switch pull policy to if not present per clayton

---

Makefile
manifests/06-operator.yaml
manifests/07-clusteroperator.yaml
pkg/apis/samples/v1/types.go
pkg/cache/upserts.go
pkg/operatorstatus/operatorstatus.go
pkg/stub/handler.go
pkg/stub/handler_test.go
pkg/stub/imagestreams.go
pkg/stub/secrets.go
pkg/stub/templates.go
test/e2e/cluster_samples_operator_test.go

Env based versioning

---

pkg/apis/samples/v1/types.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/handler_test.go
pkg/stub/secrets.go
test/e2e/cluster_samples_operator_test.go
test/e2e/main_test.go
test/framework/cvo.go

some minor areas for improvement surfaced during the recent change to env var based versioning

Improve version status

---

pkg/operatorstatus/operatorstatus.go

Fixes https://github.com/openshift/cluster-samples-operator/issues/124

enable must-gather object refs

---

tmp/build/assets/operator/ocp-x86_64/modern-webapp/imagestreams/modern-webapp-rhel7.json
tmp/build/assets/operator/ocp-x86_64/modern-webapp/templates/react-web-app-example.json
tmp/build/assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver30-tomcat7-openshift-rhel7.json
tmp/build/assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver30-tomcat8-openshift-rhel7.json
tmp/build/assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver31-tomcat7-openshift-rhel7.json
tmp/build/assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver31-tomcat8-openshift-rhel7.json
tmp/build/assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver50-tomcat9-openshift-rhel7.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-basic-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-https-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mongodb-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mongodb-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mysql-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mysql-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-postgresql-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-postgresql-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-basic-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-mongodb-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-mongodb-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-mysql-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-postgresql-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-basic-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-https-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mongodb-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mongodb-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mysql-persistent-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mysql-s2i.json
tmp/build/assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-postgresql-persistent-s2i.json

final pull from openshift/library for 4.0/4.1 GA

---

pkg/operator/controller.go
pkg/stub/handler.go
pkg/stub/handler_test.go
pkg/stub/interfaces.go
pkg/stub/templates.go

reduce gets on samples operator config object when processing template/imagestream events

---

README.md
pkg/apis/samples/v1/types.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/handler_test.go
test/e2e/cluster_samples_operator_test.go

@openshift/sig-developer-experience PTAL

Removed versioning

---

README.md
pkg/apis/samples/v1/types.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/handler_test.go
test/e2e/cluster_samples_operator_test.go

@openshift/sig-developer-experience fyi ... cherry pick of the master branch PR that just merged

 Bug 1719037: upgrades while unmanaged/removed broken

---

pkg/stub/imagestreams.go

@openshift/openshift-team-developer-experience @bparees FYI

Bug 1734627: preserve deleted EOL ISTs on upgrade

---

pkg/apis/samples/v1/types.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/handler_test.go
pkg/stub/imagestreams.go

@openshift/openshift-team-developer-experience FYI
/assign @bparees

Bug 1738256: report clusteroperator degraded if image import persists for 2 hours

---

pkg/apis/samples/v1/types.go
pkg/operatorstatus/operatorstatus.go
pkg/stub/config.go
pkg/stub/files.go
pkg/stub/handler.go
pkg/stub/handler_test.go
test/e2e/cluster_samples_operator_test.go

@bparees ptal if bandwidth permits
@openshift/openshift-team-developer-experience fyi/ptal as you are up for

DEVEXP-418: fetch arch from GOARCH, allow for z/ppc

---

.gitignore
tmp/build/assets/operator/ocp-x86_64/datagrid/templates/cache-service.json
tmp/build/assets/operator/ocp-x86_64/datagrid/templates/datagrid-service.json
tmp/build/library-sync.sh

/hold
to see if we can get upstream modified in the near term

Bug 1764219: Conv v1beta1 v1

---

tmp/build/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-example.json
tmp/build/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-persistent.json
tmp/build/assets/operator/ocp-x86_64/datagrid/templates/cache-service.json
tmp/build/assets/operator/ocp-x86_64/datagrid/templates/datagrid-service.json
tmp/build/assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-rhel7.json
tmp/build/assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-runtime-rhel7.json
tmp/build/assets/operator/ocp-x86_64/php/imagestreams/php-rhel7.json
tmp/build/assets/operator/ocp-x86_64/redis/imagestreams/redis-rhel7.json
tmp/build/assets/operator/ocp-x86_64/redis/templates/redis-ephemeral.json
tmp/build/assets/operator/ocp-x86_64/redis/templates/redis-persistent.json

@openshift/openshift-team-developer-experience fyi

Bug 1782467: bump samples since PHP EOL template updates now breaking image-eco

---

pkg/operatorstatus/operatorstatus.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/util/util.go
test/e2e/cluster_samples_operator_test.go

@openshift/openshift-team-developer-experience FYI

DEVEXP-507: bootstrap as removed for IPv6

---

manifests/03-rbac-proxies-role-binding.yaml
manifests/03-rbac-proxies-role.yaml
pkg/metrics/metrics.go
pkg/operatorstatus/operatorstatus.go
pkg/stub/handler.go
pkg/util/util.go
test/e2e/cluster_samples_operator_test.go

based on initial test runs with disconnected, proxy by @xiuwang 
@openshift/openshift-team-developer-experience @bparees fyi

DEXP-507: Ipv6 disc boot removed 2

---

manifests/03-rbac-proxies-role-binding.yaml
manifests/03-rbac-proxies-role.yaml
pkg/metrics/metrics.go
pkg/operatorstatus/operatorstatus.go
pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/handler_test.go
pkg/util/util.go
test/e2e/cluster_samples_operator_test.go

preliminary manual cherry pick of https://github.com/openshift/cluster-samples-operator/pull/214
cherrypick bot was unable to handle ... see https://github.com/openshift/cluster-samples-operator/pull/214#issuecomment-574205401
associated Jira in 4.4/master still under QE review
and in fact PRs https://github.com/openshift/cluster-samples-operator/pull/221 and https://github.com/openshift/cluster-samples-operator/pull/226 were also needed.
will update this PR as needed as that QE review progresses
/hold

Bug 1798573: bootstrap as removed for if tbr inaccessible after 3 minutes

---

manifests/08-openshift-imagestreams.yaml
manifests/image-references

Reverting #228 for master.
This reverts commit 053daf06bad2b21b47eb441a8e921c88e7c956b0.

Revert "add imagestream for oauthproxy image"

---

pkg/stub/config.go
pkg/stub/handler_test.go
pkg/util/util.go

explicitly cite file system errors, include apimachinery reason text on api server errors

Bug 1838716: improve reason text on degraded condition

---

pkg/stub/config.go
pkg/stub/handler.go
pkg/stub/imagestreams.go

manual pick to 4.3.z after bot failed ... see https://github.com/openshift/cluster-samples-operator/pull/279#issuecomment-638473451

Bug 1835996: ensure s390/ppc64le platforms bootstrap as removed following upgrade

---

Dockerfile
Dockerfile.rhel7

started to see errors in CI with the old 4.0 stuff

Bug 1853070: update base image version in dockerfiles

---

assets/operator/ocp-ppc64le/cakephp/templates/cakephp-mysql-example.json
assets/operator/ocp-ppc64le/cakephp/templates/cakephp-mysql-persistent.json
assets/operator/ocp-ppc64le/mysql/imagestreams/mysql-rhel7.json
assets/operator/ocp-s390x/cakephp/templates/cakephp-mysql-example.json
assets/operator/ocp-s390x/cakephp/templates/cakephp-mysql-persistent.json
assets/operator/ocp-s390x/mysql/imagestreams/mysql-rhel7.json
assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-example.json
assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-persistent.json
assets/operator/ocp-x86_64/mysql/imagestreams/mysql-rhel7.json
assets/operator/okd-x86_64/official/cakephp/templates/cakephp-mysql-example.json
assets/operator/okd-x86_64/official/cakephp/templates/cakephp-mysql-persistent.json
library-sync.sh

Pull in fix for https://bugzilla.redhat.com/show_bug.cgi?id=1793116
upstream version:  https://github.com/sclorg/cakephp-ex/pull/116

switch to mysql:8 and enable auth plugin needed for running in openshift

---

pkg/stub/imagestreams.go

@coreydaley we missed something in code/review that has shown up in CI this evening :-(

Bug 1898745: actually set imagestreams in progress to false in imagestream event path

---

manifests/01-namespace.yaml
manifests/010-prometheus-rules.yaml
manifests/02-sa.yaml
manifests/03-rbac-proxies-role-binding.yaml
manifests/03-rbac-proxies-role.yaml
manifests/03-rbac.yaml
manifests/04-openshift-rbac.yaml
manifests/05-kube-system-rbac.yaml
manifests/06-metricsservice.yaml
manifests/06-operator.yaml
manifests/06-servicemonitor.yaml
manifests/07-clusteroperator.yaml
manifests/08-openshift-imagestreams.yaml
manifests/09-servicemonitor-rbac.yaml

This matches openshift/enhancements#504 and doesn't change existing behavior

add 'single-node-production-edge' annotations to CVO manifests

---

README.md

/assign @bmcelvee 
in case it applies to recent doc updates you are making
admittedly at least some of these readme fixes and things I've noted in prior exchanges with you wrt to the docs 
that I failed to get to with the README

more README updates/fixes

---

README.md

@bmcelvee 
more readme fixes as I started create skills xfer videos .... I *think* these corrections are captured in recent doc PRs, but am not as certain as I was with the PR from yesterday
@pedjak @akashshinde @Avni-Sharma 
these are the readme changes I discovered were needed after my first skills xfer video I just sent you :-)

more readme corrections stemming from skills transfer work

---

manifests/010-prometheus-rules.yaml
pkg/metrics/metrics.go

Bug 1914723: SamplesTBRInaccessibleOnBoot Alert has a misspelling

---

manifests/01-namespace.yaml
manifests/010-prometheus-rules.yaml
manifests/02-sa.yaml
manifests/03-rbac-proxies-role-binding.yaml
manifests/03-rbac-proxies-role.yaml
manifests/03-rbac.yaml
manifests/04-openshift-rbac.yaml
manifests/05-kube-system-rbac.yaml
manifests/06-metricsservice.yaml
manifests/06-operator.yaml
manifests/06-servicemonitor.yaml
manifests/07-clusteroperator.yaml
manifests/08-openshift-imagestreams.yaml
manifests/09-servicemonitor-rbac.yaml

Bug 1948782: revert single-node-production-edge annotation

---

pkg/metrics/metrics.go
pkg/stub/files.go
pkg/stub/handler.go
pkg/stub/handler_test.go
pkg/stub/imagestreams.go
pkg/stub/interfaces.go
pkg/stub/templates.go
pkg/util/util.go

adjust fsm status update grouping to account for deepcopies
reduce logging

Bug 1949481: add DeepCopy to avoid SharedInformer cache mutation

---

pkg/stub/imagestreams.go
pkg/stub/templates.go
pkg/util/util.go

Bug 1993840: avoid immediate degraded on intermittent API errors; set reason/message when Available=false

---

OWNERS

/assign @dperaza4dustbit 
@dperaza4dustbit - the first test for your new privileges will be constructing a PR that adds whomever else you want as approver/reviewer ;-)
1) do you want to be removed as an approver?
2) are you amenable to adding the valid bz label :-) ? .... adding @dperaza4dustbit as part of transferring samples to his team

add david peraza as approver, clean up reviewers

---

pkg/stub/handler.go
pkg/stub/imagestreams.go
pkg/stub/templates.go

Missed some spots with https://github.com/openshift/cluster-samples-operator/pull/387/files
/assign @dperaza4dustbit

Bug 1993840: more avoiding immediate degraded on intermittent API errors

---

pkg/stub/imagestreams.go
pkg/stub/templates.go

will take an lgtm from any one of you :-) 
/assign @stbenjam 
/assign @dperaza4dustbit 
/assign @coreydaley 
thanks !

Bug 2003683: fix recently introduced panic when conflict errors occur

---

pkg/stub/handler.go
pkg/stub/handler_test.go

By default the configured sample registry is empty. This is causing
image stream creating at update time to fail even when the allowed
image registries include registry.redhat.io, registry.access.redhat.com
and quay.io. This PR takes care of the default scenario.

Bug 2027745: Allowing ImageStream creation when config registry empty

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Bumping prometheus client_golang to v1.11.1 where CVE is fixed.

Bug 2067823: Taking care of CVE-2022-21698

---

OWNERS

Adding Feny's name to the Owners file
Signed-off-by: Feny Mehta <fbm3307@gmail.com>

Bug 2095256: Samples Owner needs to be Updated

---

assets/operator/ocp-aarch64/nginx/imagestreams/nginx-rhel-aarch64.json
assets/operator/ocp-ppc64le/nginx/imagestreams/nginx-rhel.json
assets/operator/ocp-ppc64le/sso/imagestreams/sso76-openshift-rhel8.json
assets/operator/ocp-ppc64le/sso/templates/sso76-https.json
assets/operator/ocp-ppc64le/sso/templates/sso76-ocp3-x509-https.json
assets/operator/ocp-ppc64le/sso/templates/sso76-ocp3-x509-postgresql-persistent.json
assets/operator/ocp-ppc64le/sso/templates/sso76-ocp4-x509-postgresql-persistent.json
assets/operator/ocp-ppc64le/sso/templates/sso76-postgresql.json
assets/operator/ocp-s390x/nginx/imagestreams/nginx-rhel.json
assets/operator/ocp-s390x/sso/imagestreams/sso76-openshift-rhel8.json
assets/operator/ocp-s390x/sso/templates/sso76-https.json
assets/operator/ocp-s390x/sso/templates/sso76-ocp3-x509-https.json
assets/operator/ocp-s390x/sso/templates/sso76-ocp3-x509-postgresql-persistent.json
assets/operator/ocp-s390x/sso/templates/sso76-ocp4-x509-https.json
assets/operator/ocp-s390x/sso/templates/sso76-ocp4-x509-postgresql-persistent.json
assets/operator/ocp-s390x/sso/templates/sso76-postgresql-persistent.json
assets/operator/ocp-s390x/sso/templates/sso76-postgresql.json
assets/operator/ocp-x86_64/nginx/imagestreams/nginx-rhel.json
assets/operator/ocp-x86_64/sso/imagestreams/sso76-openshift-rhel8.json
assets/operator/ocp-x86_64/sso/templates/sso76-https.json
assets/operator/ocp-x86_64/sso/templates/sso76-ocp3-x509-https.json
assets/operator/ocp-x86_64/sso/templates/sso76-ocp3-x509-postgresql-persistent.json
assets/operator/ocp-x86_64/sso/templates/sso76-ocp4-x509-https.json
assets/operator/ocp-x86_64/sso/templates/sso76-ocp4-x509-postgresql-persistent.json
assets/operator/ocp-x86_64/sso/templates/sso76-postgresql-persistent.json
assets/operator/ocp-x86_64/sso/templates/sso76-postgresql.json
assets/operator/okd-x86_64/nginx/imagestreams/nginx-centos.json

Signed-off-by: Feny Mehta <fbm3307@gmail.com>

OCPBUGS-4166: Update Cluster Sample Operator dependencies and libraries for OCP 4.13

---

assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json

OCPBUGS-6579: update sample imagestreams with latest 4.11 image using specific image tag reference

---

OWNERS

Following https://github.com/openshift/ocp-build-data/pull/2639/files, adjust Jira component.

Fix jira component

---

assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json

Coincides with https://github.com/openshift/library/pull/349/files

OCPBUGS-15754: Update Jenkins and Jenkins Agent Base image versions

---

OWNERS

Add more owners 
Jira: https://issues.redhat.com/browse/OCPBUGS-38159

OCPBUGS-38159: add owners

---

manifests/06-operator-ibm-cloud-managed.yaml
manifests/06-operator.yaml

[OCPBUGS-37464](https://issues.redhat.com/browse/OCPBUGS-37464)
Cherry-pick of #535

[release-4.15] OCPBUGS-37464: Set required-scc for openshift workloads

---

OWNERS

[release-4.14] OCPBUGS-49421: add shannon and aroyoredhat as owners

---

OWNERS

[release-4.13] OCPBUGS-49663: add shannon and aroyoredhat as owners

---

OWNERS

[release-4.12] OCPBUGS-49664: add shannon and aroyoredhat as owners

---

go.mod
go.sum
vendor/golang.org/x/oauth2/LICENSE
vendor/golang.org/x/oauth2/README.md
vendor/golang.org/x/oauth2/oauth2.go
vendor/golang.org/x/oauth2/pkce.go
vendor/golang.org/x/oauth2/token.go
vendor/modules.txt

Reverts openshift/cluster-samples-operator#606

OCPBUGS-52848: Unrevert the revert "OCPBUGS-52346: bump x/oauth2 to version 0.27.0"

---

assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-runtime.json
assets/operator/okd-x86_64/dotnet/imagestreams/dotnet.json
assets/operator/okd-x86_64/nodejs/imagestreams/nodejs-centos.json
assets/operator/okd-x86_64/openliberty/imagestreams/openliberty.json

Syncing the latest samples from the library to OKD.
Created using https://github.com/metlos/trigger-test-samples-build

OCPBUGS-54479: Periodic sync of OKD samples

---

assets/operator/ocp-aarch64/dotnet/imagestreams/dotnet-rhel-aarch64.json
assets/operator/ocp-aarch64/dotnet/imagestreams/dotnet-runtime-rhel-aarch64.json
assets/operator/ocp-aarch64/nodejs/imagestreams/nodejs-rhel-aarch64.json
assets/operator/ocp-ppc64le/dotnet/imagestreams/dotnet-rhel-ppc64le.json
assets/operator/ocp-ppc64le/dotnet/imagestreams/dotnet-runtime-rhel-ppc64le.json
assets/operator/ocp-ppc64le/nodejs/imagestreams/nodejs-rhel.json
assets/operator/ocp-s390x/dotnet/imagestreams/dotnet-rhel-s390x.json
assets/operator/ocp-s390x/dotnet/imagestreams/dotnet-runtime-rhel-s390x.json
assets/operator/ocp-s390x/nodejs/imagestreams/nodejs-rhel.json
assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-rhel.json
assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-runtime-rhel.json
assets/operator/ocp-x86_64/nodejs/imagestreams/nodejs-rhel.json

Syncing the latest supported OCP samples from the library.
Created using https://github.com/metlos/trigger-test-samples-build

OCPBUGS-54471: Periodic sync of supported OCP samples

---

pkg/operatorstatus/operatorstatus.go

Samples Operator should update the LastTransitionTime only if the status of the operator changes.

OCPBUGS-54591: only update LastTransitionTime if operator status change

---

pkg/operator/controller.go

Adding a filter to only trigger it there are events with openshift-samples on clusterOperatorInformerEventHandler

OCPBUGS-54589: Adding filter to clusterOperatorInformerEventHandler

---

OWNERS

This is a manual cherry pick of #624

[release-4.13] OCPBUGS-54812: add rhdmalone to owners
