openshift/cluster-samples-operator

- deploy/02-rbac.yaml
Anybody using these manfiests doesn't have information or context
to find which namespace these Namespaced Object need to be installed.
For example, ClusterVersionOperator wouldn't know which namespace to choose.
> deploy: add namespace to Role and RoleBindings

- pkg/stub/handler.go
- pkg/stub/handler_test.go
Fixes https://github.com/openshift/cluster-samples-operator/issues/21
Looks good with live testing in addition to unit test
> proper toggling of error messages with ConfigurationValid condition

- cmd/cluster-samples-operator/main.go
- pkg/apis/samplesoperator/v1alpha1/types.go
- pkg/operatorstatus/operatorstatus.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
includes comment detailing my failed attempts to use the current sdk version vendored in to watch imagestreams and templates ... not just using "v1" as the api version failed (though with a basic could not find the resource error) ... the `k8sutil.RuntimeObjectFromUnstructured` is what bombs trying to convert the json payload into a go struct/obj.
> add samples watches; fix sdk get/upd/create retry; other minor fixes

- pkg/apis/samplesoperator/v1alpha1/types.go
- pkg/operatorstatus/operatorstatus.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
@openshift/sig-developer-experience 
NOTE - I did not add e2e tests yet because the "in between state" of clusteroperator wrt its groups etc. is causing odd behavior in my test cluster ... via debug, I'm confirming that creation/update of the object is happening, but "oc get clusteroperator" returns no resources
the samplesresource updates are working just fine, but I'd rather add the tests all at once
I'll refresh the installer and update deps here as the clusteroperator situation progresses, and add e2e's accordingly.
> add progressing cluster status (imagestreams only)

- README.md
The name of secret for openshift-cluster-samples-operator project should be '[samples-registry-credentials'](https://github.com/openshift/cluster-samples-operator/blob/master/pkg/apis/samplesoperator/v1alpha1/types.go#L40)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656689
> Modify the secret name and some tiny typos

- pkg/apis/samples/v1/types.go
built on https://github.com/openshift/cluster-samples-operator/pull/77 and https://github.com/openshift/cluster-samples-operator/pull/76 which are still fighting merge queue flakes
> godoc/value consistency fixes for types via wewang/bparees

- deploy/05-operator.yaml
- deploy/image-references
- pkg/stub/interfaces.go
- pkg/stub/jenkins.go
ptal to review at least the yaml/ref stuff
in theory we could just merge this, but ideally I can wire in the processing of the new env's in the samples operator code with this PR as well
I'd like to start on those after https://github.com/openshift/cluster-samples-operator/pull/81
> add image refs, env vars, so we can get jenkins images from payload

- Dockerfile
- Dockerfile.rhel7
- deploy/06-openshift-imagestreams.yaml
- deploy/image-references
Add installer, which was the next dependency we need to include with
the cluster.
@bparees I realized that having where it is now (in the cli image) is a big
problem because everyone who descends from the cli image was getting added
multiple times during release creation, including jenkins agents. Once this moves
I can delete it out of origin.
> Move the cli image stream into samples operator

- tmp/build/assets/operator/ocp-x86_64/dotnet/templates/dotnet-pgsql-persistent.json
- tmp/build/assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel7.json
- tmp/build/assets/operator/okd-x86_64/dotnet/templates/dotnet-pgsql-persistent.json
- tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-centos7.json
this should get rid of jenkins-1-*
> bump openshift/library import (pick up jenkins-1 removal)

- pkg/cache/upserts.go
Based on the investigation from https://github.com/openshift/cluster-samples-operator/issues/100 increasing the time we hold onto the startup cache during the initial install could help reduce some of the api churn
Saw a decent amount of `have not received an upsert event for...` messages in my analysis of the startup runs today.
/assign @bparees
> bump cache window to account for timing data from initial installs

- pkg/cache/upserts.go
- pkg/stub/config.go
- pkg/stub/handler.go
- pkg/stub/imagestreams.go
as before, the first 2 commits are other PRs we are trying to merge separately, but touch the same files
/assign @bparees
> Upsert opts

- pkg/apis/samples/v1/types.go
in addition to the fix discussed in slack, I'm addressing one of Seth's findings re cvo status (testing that lead me to discover the startup regression ... confirmed first commit did not cause regressions)
> Cvo tweaks

- manifests/05-kube-system-rbac.yaml
- pkg/operator/controller.go
- pkg/stub/handler.go
- pkg/stub/secrets.go
The operator should be using the openshift-config/pull-secret as the kube-system/coreos-pull-secret has been marked deprecated.
> BUG 1697644: operator: use openshift-config/pull-secret to fetch the pull secret

- manifests/06-operator.yaml
- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
They will be used by `oc adm release extract --tools` to get windows
and mac binaries for oc and installer.
In addition, fix the input images to be consistent and use quay.
> Add the cli-artifacts and installer-artifacts images to the payload

- manifests/01-namespace.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
> Add node-selector annotation to namespace

- manifests/06-operator.yaml
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
> Fix tolerations

- pkg/operatorstatus/operatorstatus.go
thanks @dmage for heads up
Now looks like:
```
gmontero ~ $ oc get clusteroperator openshift-samples -o yaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
creationTimestamp: "2019-05-06T19:16:47Z"
generation: 1
name: openshift-samples
resourceVersion: "80560"
selfLink: /apis/config.openshift.io/v1/clusteroperators/openshift-samples
uid: 7e080c2f-7033-11e9-a8ac-0a985de94f40
spec: {}
status:
conditions:
- lastTransitionTime: "2019-05-06T19:17:34Z"
message: Samples installation successful at 4.1.0-0.okd-2019-05-06-134910
status: "True"
type: Available
- lastTransitionTime: "2019-05-06T19:17:34Z"
message: Samples installation successful at 4.1.0-0.okd-2019-05-06-134910
status: "False"
type: Progressing
- …
```
> fix clusteroperator related-objects, set with updatestatus vs. create

- manifests/03-rbac.yaml
@openshift/openshift-team-developer-experience fyi ... I think image-registry-operator and openshift-controller-manager-operator could use this as well for the cfg objs ...thoughts?
/assign @enj 
@enj - if you have the cycles, PTAL as well, but conversely I can unassign you if you like
> Bug 1717124: add clusterrole to allow cluster-reader access to the samples config obj

- Makefile
- manifests/00-crd.yaml
This pulls updates driven my master team through https://bugzilla.redhat.com/show_bug.cgi?id=1712317 to get full godoc transfer to the config  CRD used by `oc explain`
@openshift/openshift-team-developer-experience FYI
> update crd schema usage to get full descriptions for oc explain

- pkg/operatorstatus/operatorstatus.go
- pkg/stub/handler_test.go
@openshift/openshift-team-developer-experience @bparees FYI / PTAL
see line 97 for the params defined for `setOperatorStatus`
> Bug 1739214:  set degraded reason/msg on cluster operator obj when degraded==true

- manifests/image-references
This adds the baremetal-installer to image-references so it is included
in releases.
> Add baremetal-installer to image-references

- manifests/image-references
This reverts commit f070c1458e47c32db783058711a25fca7f725cea, #170
It's failing for [ART-built nightlies][1]:
```
error: unable to create a release: operator "cluster-samples-operator" contained an invalid image-references file: no input image tag named "baremetal-installer"
```
[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4.2.0-0.nightly/release/4.2.0-0.nightly-2019-08-14-154809
> Revert "Add baremetal-installer to image-references"

- manifests/image-references
This adds the baremetal-installer to image-references so it is included
in releases.
> Add reference to baremetal-installer

- pkg/apis/samples/v1/types.go
- pkg/operatorstatus/operatorstatus.go
the automatic cherry-pick from the last 4.2 PR did not work:  https://github.com/openshift/cluster-samples-operator/pull/167#issuecomment-522238466
that said, two commits from 4.2 were needed to fix missing reason details for cluster operator conditions for the samples operator - those commits were picked 
but also, @bparees and I previously discussed that we should *NOT* backport the "feature" around marking samples operator degraded if imagestream imports have been failing for two hours
as such, some of the changes from the two 4.2 PRs were dropped
/assign @bparees (as we discussed various particulars of what to merge back in https://bugzilla.redhat.com/show_bug.cgi?id=1741069)
@openshift/openshift-team-developer-experience fyi
> Bug 1742907: Degraded missing reason detail 41

- pkg/apis/samples/v1/types.go
in service of extended test flake https://bugzilla.redhat.com/show_bug.cgi?id=1745418
adding the specific imagestream import failures in the detailed message for clusteroperator detailed/progressing conditions is more useful then pointing admins to the config object
also, we can check in our extended tests to see which imagestreams failed when determining whether the test run is safe to continue  ... I'll be submitting a openshift/origin PR that does that and resolves https://bugzilla.redhat.com/show_bug.cgi?id=1745418 after this merges 
@openshift/openshift-team-developer-experience  FYI
> add list of imagestreams failing import to progressing/degraded detailed message

- pkg/operatorstatus/operatorstatus.go
- pkg/stub/handler.go
- pkg/stub/imagestreams.go
- pkg/stub/templates.go
@openshift/openshift-team-developer-experience 
among other things, if we were in the middle of imagestream imports when the delete occurred, I could see *SOME* delays though not 5 minutes
but there may have been some missed opportunities to update the condition because the code did not think it was modified
also adding some more proactive updating and some removal of retry on samples events
> Bug 1749152: close gaps for updating clusteroperator during delete of config object

- Makefile
- manifests/00-crd.yaml
- pkg/apis/samples/v1/types.go
Use of the cherrpick bot was untenable for this bugzilla because it took 2 commits across 2 PRs in master branch post-4.1 GA to get `oc explain` for the samples config CR to be fully functional.
Those master/4.2 PRs were
- https://github.com/openshift/cluster-samples-operator/pull/148
- https://github.com/openshift/cluster-samples-operator/pull/161
We did not need https://github.com/openshift/cluster-samples-operator/pull/144 as it was obsoleted by https://github.com/openshift/cluster-samples-operator/pull/161
backporting request came from @sferich888 
@openshift/openshift-team-developer-experience @bparees FYI
> Bug 1743376: Missing openapi CRD definitions for oc explain to work for sample operator CRD

- pkg/operatorstatus/operatorstatus.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/util/util.go
> Bug 1779933: set version to start for s390/ppc until we have actual samples

- pkg/operatorstatus/operatorstatus.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
manual pick of https://github.com/openshift/cluster-samples-operator/pull/205 since there are enough discrepancies between 4.2 and 4.4 such that the cherrypick bot can't handle it automatically
see https://github.com/openshift/cluster-samples-operator/pull/205#issuecomment-562299925
Note, still waiting on final lgtm for https://github.com/openshift/cluster-samples-operator/pull/205 as well as passing e2e's and merge.
I'll update this PR/commit if need be as the master branch PR progresses
@jwforres @sosiouxme FYI
> Bug 1779935: set version to start for s390/ppc until we have actual samples

- tmp/build/assets/operator/ocp-x86_64/java/imagestreams/openjdk-8-rhel8-rhel7.json
I've seen the import fail in multiple installs since last Friday, as have others in 4-dev-triage, etc. and docker pulls from my laptop are proving very very flaky
@openshift/openshift-team-developer-experience @bparees fyi
after this merges I'll craft a re-enablement PR and between that and local pulls see if/when it stabilizes
it is still listed as a valid option in the container catalog
> Bug 1788612: temp disable of openjdk-8-11 while it seems busted on registry.redhat.io

- pkg/stub/config.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/util/util.go
The original design point in samples operator about delaying `Removed` management state processing until imagestreams imports completed has ended up proving untenable since 
- we now retry failed imports more than once 
- with disconnected  or misconfigured proxy installs, it is now very possible that imports will *NEVER* succeed out of the gate
QE's disconnected CI runs revealed this.
This PR pivots to process `Removed` immediately.
Some additional needs also arose between additional QE testing and my testing:
- for our TBR credential metrics, we can avoid logging chatter by seeing if Removed/Unmanaged
- the bootstrap as removed with disconnected/ipv6 changes we just merged (https://github.com/openshift/cluster-samples-operator/commit/1afe3cf6583b3a52b686a11d6df05046231eff16) had a …
> Bug 1782683: no longer gate removed processing when imagestreams in progress

- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
> Revert "add imagestream for oauthproxy image"

- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
The tools image is the base for 'tests' and will be used by default
for debug, ensuring that admins get a fast and quick deploy (because
the base image is reused). We will add necessary administrative tools
to the image over time to ensure admins are happy.
/hold
until the image is available in OSBS and the nightly streams
> manifests: Add the new 'tools' image as an image stream for debug

- pkg/apis/samples/v1/types.go
- pkg/stub/config.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
Manual pick of https://github.com/openshift/cluster-samples-operator/pull/220 for 4.2.z
cherrypick bot failed ..... see https://github.com/openshift/cluster-samples-operator/pull/220#issuecomment-589697147
> [release-4.2] Bug 1805615: no longer gate removed processing when imagestreams in progress

- pkg/stub/handler_test.go
- pkg/stub/secrets.go
- test/e2e/cluster_samples_operator_test.go
> Bug 1818476: copy install pull secret when boostrapped as removed

- pkg/stub/imagestreams.go
Details in bz, but with import stream via sha in, we don't need to override the jenkins image stream registry to support disconnected, and that gets in the way in other scenarios
@openshift/openshift-team-developer-experience fyi
see https://github.com/openshift/cluster-samples-operator/pull/177
> Bug 1822381: revert pr 177; no override jenkins* registry hosts for mirrors

- pkg/stub/handler.go
- pkg/stub/handler_test.go
basically https://github.com/openshift/cluster-samples-operator/pull/240 was incomplete with respect to samples that are removed from release to release
there is a window where removed templates can gum up the works where repeated attempts to process removed templates result in repeated 
```
time="2020-04-27T06:43:12Z" level=info msg="open : no such file or directory error reading file []"
time="2020-04-27T06:43:12Z" level=info msg="CRDUPDATE event temp udpate err"
```
which leads to a storm of addtional updates to the samples operator config object 
that can severely slow down getting the progressing condition to false
@bparees I assigned you in case you want this expedited and included in 4.4.0 ... I'm guessing the answer to that is "no" based on …
> Bug 1828065: correctly handle removed templates watch events as part of an upgrade

- pkg/stub/config.go
file list gets executed on s390x/ppc64le upgrade even when mgmt state removed
placeholder and potential backport candidate while we work on getting s390x/ppc64le samples into 4.5 and/or 4.6
> Bug 1835112: avoid listing file system content for unsupported architures

- pkg/stub/handler.go
- pkg/stub/handler_test.go
Had to initiate manual pick of https://github.com/openshift/cluster-samples-operator/pull/265 and https://github.com/openshift/cluster-samples-operator/pull/265/commits/803f09300a304c3977f79a90d8b32b29fe94bc7d into 4.4 after automanted cherrpick bot failed ... see https://github.com/openshift/cluster-samples-operator/pull/265#issuecomment-624698661 for that failure
In addition to normal motivations for back picking upgrade fixes, this problem came up during an apparent etcd breakdown -> openshift apiserver breakdown -> samples could not create/update imagestream/template breakdown that was worked via https://coreos.slack.com/archives/C0134TXLGG3/p1588759278000200 while I was out on bereavement
@vrutkovs FYI
> Bug 1832344: correctly handle removed templates watch events as part of an upgrade

- pkg/stub/config.go
- pkg/stub/handler.go
- pkg/stub/imagestreams.go
/hold 
until @dbenoit17 and I verify these changes via a 4.3 based branch he is testing on s390 for me
> Bug 1835112: ensure s390/ppc64le platforms bootstrap as removed following upgrade

- cmd/cluster-samples-operator/main.go
- pkg/client/listers.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/operator/controller.go
- pkg/operatorstatus/operatorstatus.go
- pkg/stub/config.go
- pkg/stub/files.go
- pkg/stub/finalizer.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/stub/imagestreams.go
- pkg/stub/interfaces.go
- pkg/stub/jenkins.go
- pkg/stub/retry.go
- pkg/stub/templates.go
- pkg/util/util.go
- test/e2e/cluster_samples_operator_test.go
- test/e2e/main_test.go
Sort and partition the existing go imports to align with
OpenShift organization standards.
No other changes were done except for the go imports reorganization.
> Standardize go imports

- pkg/stub/config.go
- pkg/stub/handler_test.go
- pkg/util/util.go
replacement of automated cherry-pick of https://github.com/openshift/cluster-samples-operator/pull/275
see https://github.com/openshift/cluster-samples-operator/pull/281#issuecomment-636918855 for details on the need
reader's digest version:  install pull creds no longer needed in 4.5 but still are in 4.4
> [release-4.4] Bug 1842560: improve reason text on degraded condition

- pkg/stub/config.go
- pkg/stub/handler.go
- pkg/stub/imagestreams.go
manual pick after cherrybot failure https://github.com/openshift/cluster-samples-operator/pull/277#issuecomment-635407445
> Bug 1835995: ensure s390/ppc64le platforms bootstrap as removed following upgrade

- pkg/stub/handler_test.go
- pkg/stub/imagestreams.go
Currently, when defining samplesRegistry in the CR with a value of newhost:1111/path, the resulting imageStream DockerImage values become newhost:1111/path/path/path instead of newhost:1111/path/oldpaths.
This PR makes it possible to have a path in samplesRegistry in the CR. This could be beneficial when using external registries with paths (e.g. Artifactory remote registries).
> Fix samplesRegistry replacement in imageStreams when using paths

- pkg/metrics/metrics.go
- pkg/metrics/server.go
- pkg/metrics/server_test.go
- pkg/stub/imagestreams.go
motivated by the debuggability initiative started reviewing things for samples
we actually have a lot already there when you look at 
- invalid config indications in operator, metrics
- other metrics
-- which imagestreams have failed imports
-- are tbr creds missing from the install pull secret
-- was the tbr inaccessible on initial install
- must gather data
-- openshift imagestream yaml grabbed
-- pod logs, config/operator grabbed
- reason/message usage when degraded/progressing
-- different reasons around failed import vs. api server error (with specific error in reason) vs. file system error 
-- imagestream error snipptes in message
-- last retry time in message
but a more explicit indication that we are retrying failed imports as expected on our periodic basis, vs. just confirming in …
> [BUILD-92] add import retry count into metrics

- pkg/stub/handler.go
- pkg/stub/handler_test.go
So we finally got an intermittent situation when the api server was momentarily unavailable during an upgrade when samples operator tried to upsert new samples.
In setting the error condition, the code (since 4.1 I believe) set the error on the ImageChangesInProgress condition.
However, that results in text in the reason field which would not get cleared as we start tracking import completion in the ImageChangesInProgress reason field.  As it never gets cleared, we never set Progressing to false.
The pattern in samples operator is to set these errors in SamplesExists, as that reflects whether samples are fully created/up to date.
This PR hence fixes this single inconsistency.  I went back and confirmed this was the only place this situation was occurring.
Also added some additional unit …
> Bug 1854857: initial create errors should map to SamplesExists instead of ImageChangesInProgress

- Makefile
- test/e2e/cluster_samples_operator_test.go
A force merge or test override is likely needed since the okd-e2e-aws-operator job in openshift/release needs to validate against the new `make test-e2e-okd`
@vrutkovs @yselkowitz FYI
aside from the rehearsals in my https://github.com/openshift/release/pull/11340, we'll validate against @yselkowitz 's https://github.com/openshift/cluster-samples-operator/pull/317 and the updated UBI8 based OKD content
> Bug 1872080: add new okd e2e to validate okd vs. ocp content is installed

- pkg/stub/handler.go
- pkg/stub/handler_test.go
This PR is needed to replace #314 from the cherrypick bot because of differences in behavior between 4.4 and 4.5/4.6
We copy creds and track that condition in 4.4, but no longer do so in 4.5/4.6, so the unit tests in 4.4 need an additional step of adding the necessary security conditions via a call to `processCred` to bypass that short circuit so we can get to validating the template / imagestream upsert error logic.
See detailed triage in https://github.com/openshift/cluster-samples-operator/pull/314#issuecomment-679110733
> [release-4.4] Bug 1871832: initial create errors should map to SamplesExists instead of ImageChangesInProgress

- Dockerfile
Updating ose-cluster-samples-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-samples-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
> Updating ose-cluster-samples-operator builder & base images to be consistent with ART

- README.md
- manifests/010-prometheus-rules.yaml
- pkg/client/listers.go
- pkg/operator/controller.go
- pkg/operatorstatus/operatorstatus.go
- pkg/stub/config.go
- pkg/stub/files.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/stub/interfaces.go
- pkg/util/util.go
- test/e2e/cluster_samples_operator_test.go
@bparees @sbose78 @adambkaplan @coreydaley @otaviof @bmcelvee 
this PR introduces a configmap into the samples operator namespace that has imagestreamtag to image mappings for the samples inventory ... basically I liked @bparees 's idea better than mine in slack :-)
it stems from the exchange in openshift-sme around trying to use the existing documentation's use of `oc` on a "connected" cluster to get the list of images to mirror in a disconnected cluster
this configmap will get created even in a disconnected cluster that bootstraps as removed
if we deliver this, we'd want to update the OCP docs to replace the current directions for obtaining image refs with directions on utilizing this new config map
Also, some seed planting @bparees @sbose78 @adambkaplan with 4.7 planning coming up:
- I …
> BUILD-145: store imagestreamtag to image mappings in configmap

- manifests/06-operator.yaml
- manifests/image-references
- pkg/stub/imagestreams.go
- pkg/stub/jenkins.go
Just like jenkins-agent-maven and jenkins-agent-nodejs, derive the
pullspec for jenkins-agent-base from the release payload.
I'm thinking this should be backported to 4.6 as well so that it doesn't
start picking up 4.7+ versions once those GA.
> Bug 1886890: Override jenkins-agent-base imagestream

- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
This should make it easier for existing uses of hello-openshift to move
to the official image (just added to 4.7).
/cc @sgreene570
> Add hello-openshift imagestream

- manifests/01-namespace.yaml
- manifests/010-prometheus-rules.yaml
- manifests/02-sa.yaml
- manifests/03-rbac-proxies-role-binding.yaml
- manifests/03-rbac-proxies-role.yaml
- manifests/03-rbac.yaml
- manifests/04-openshift-rbac.yaml
- manifests/05-kube-system-rbac.yaml
- manifests/06-metricsservice.yaml
- manifests/06-operator.yaml
- manifests/06-servicemonitor.yaml
- manifests/07-clusteroperator.yaml
- manifests/08-openshift-imagestreams.yaml
- manifests/09-servicemonitor-rbac.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
> add current profile annotations to CVO manifests

- README.md
- pkg/stub/config.go
- pkg/stub/configmap.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/stub/imagestreams.go
- test/e2e/cluster_samples_operator_test.go
Seen a few runs in CI today for various repos fail where the the samples operator did not get out of progressing == true state
When examining the pods logs, some odd message after our attempt to update progressing to false after getting a configmap delete event failed:
```
2020-11-12T17:29:36.043718980Z W1112 17:29:36.043675      16 reflector.go:424] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: watch of *v1.ImageStream ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 225; INTERNAL_ERROR") has prevented the request from succeeding
2020-11-12T17:29:45.622049521Z time="2020-11-12T17:29:45Z" level=info msg="CRDERROR progressing false update"
2020-11-12T17:29:45.622089759Z …
```
> set progressing false on imagestream events as well if no active streams

- README.md
- pkg/stub/config.go
- pkg/stub/configmap.go
- pkg/stub/files.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- test/e2e/cluster_samples_operator_test.go
/hold 
during the analysis of upgrade issues exposed via search.ci that lead to https://github.com/openshift/cluster-samples-operator/pull/340
another simplification occurred to me that goes with our move off of tracking conditions on the samples operator cluster scoped config resource  .... deprecating the `ImageChangesInProgress` condition and use the newer approaches for tracking imagestream status, as well as the approach started in 4.6 of not gating the report of being ready to the CVO, namely
- active == true
- progressing == false
- degraded == false
- version set
on the state of imagestreams after we have created them (i.e. their imports do not gate the process)
Now, so far (after about 15 hours),  since #340 merged, the samples upgrade has appeared clean on search.ci, so I'm not …
> Bug 1898745: deprecate ImageChangesInProgress, make sure it stays false

- manifests/01-namespace.yaml
- manifests/010-prometheus-rules.yaml
- manifests/02-sa.yaml
- manifests/03-rbac-proxies-role-binding.yaml
- manifests/03-rbac-proxies-role.yaml
- manifests/03-rbac.yaml
- manifests/04-openshift-rbac.yaml
- manifests/05-kube-system-rbac.yaml
- manifests/06-metricsservice.yaml
- manifests/06-operator.yaml
- manifests/06-servicemonitor.yaml
- manifests/07-clusteroperator.yaml
- manifests/08-openshift-imagestreams.yaml
- manifests/09-servicemonitor-rbac.yaml
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-samples-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.
> Annotate manifests for single-node-developer cluster profile

- manifests/06-operator.yaml
patterned off of fellow control pane component https://github.com/openshift/cluster-openshift-apiserver-operator/blob/master/manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
> Bug 1905319: request required minimal mem resource per openshift conventions

- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
- Set local lookup policy on CVO manifests
- Update hello-openshift pullspec in CVO manifests
> Bug 1766287: Improve usability of hello-openshift imagestream

- manifests/01-namespace.yaml
- manifests/06-operator-ibm-cloud-managed.yaml
- manifests/06-operator.yaml
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Add management workload annotations

- assets/operator/okd-x86_64/nginx/imagestreams/nginx-centos.json
- assets/operator/okd-x86_64/ruby/imagestreams/ruby-centos.json
This would ensure the clusters are hitting docker.io less often. Centos8 images are not yet mirrored to quay.
TODO:
Failure summary:
* `okd-e2e-aws-jenkins` - `[sig-arch] Only known images used by tests`:
```
Cluster accessed images that were not mirrored to the testing repository or already part of the cluster, see test/extended/util/image/README.md in the openshift/origin repo:  quay.io/redhat-developer/nfs-server:latest from pods:   ns/e2e-test-jenkins-pipeline-v7nsz pod/nfs-server node/ip-10-0-139-183.us-east-2.compute.internal
```
Not sure what's up with that, this PR doesn't touch tests
> Bug 1950236: OKD: replace some docker.io images with quay.io

- pkg/metrics/metrics.go
- pkg/stub/files.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/stub/imagestreams.go
- pkg/stub/interfaces.go
- pkg/stub/templates.go
- pkg/util/util.go
adjust fsm status update grouping to account for deepcopies
reduce logging
manual pick of https://github.com/openshift/cluster-samples-operator/pull/369 for 4.7.z
bz set up so bots don't work well
> Bug 1950808: add DeepCopy to avoid SharedInformer cache mutation

- manifests/06-operator-ibm-cloud-managed.yaml
- manifests/06-operator.yaml
As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged
> Rename workload annotations

- pkg/metrics/metrics.go
- pkg/stub/files.go
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/stub/imagestreams.go
- pkg/stub/interfaces.go
- pkg/stub/templates.go
- pkg/util/util.go
- test/e2e/cluster_samples_operator_test.go
add DeepCopy to avoid SharedInformer cache mutation
no longer track in progress reason incrementally
as soon as imagestream reports in mark it as off the in progress list
clear our reason field only when all imagestreams report in
manual version of https://github.com/openshift/cluster-samples-operator/pull/370 ... the samples rewrite in 4.7 makes cherrypick bot untenable
also, based on 4.6 specifcs, the second commit adds some 4.6 unique optimizations for the in progress reason field where are no longer applicable after the 4.7 rework
> Bug 1950809: add DeepCopy to avoid SharedInformer cache mutation

- manifests/06-servicemonitor.yaml
Invalid selector in ServiceMonitor makes CVO attempt to apply this manifest on every sync iteration
> Bug 1960334: manifests: fix selector in ServiceMonitor

- manifests/07-clusteroperator.yaml
Per http://mailman-int.corp.redhat.com/archives/aos-devel/2021-May/msg00139.html from @wking 
Note:  the operator fills out `RelatedObjects` in https://github.com/openshift/cluster-samples-operator/blob/c1b73fe82b9bee65b28f886dcc930a5205680d6c/pkg/operatorstatus/operatorstatus.go#L226-L230
> seed relatedObjects in manifest yaml

- manifests/08-openshift-imagestreams.yaml
/assign @jottofar 
@jottofar please lgtm if I have interpreted https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/object-deletion.md and this bz correctly
I'm guessing I don't need to update `image-references` as well since this change is intended for deletion, but we'll see how the cluster install goes.  If there are complaints from the CVO around samples operator then that is the most likely explanation.
@dperaza4dustbit FYI ... these "in payload" imagestreams IIRC are also discussed in the skill xfer videos.
> Bug 1975539: delete hello-openshift in payload imagestream via CVO annotation

- pkg/stub/handler.go
> Bug 1990140: add connection with timeout in TBR accessibility check to expedite 'disconnected' mode

- pkg/stub/handler.go
/assign @coreydaley 
@dperaza4dustbit FYI - we missed something in code/review
also decided to bump retry slightly
> Bug 1995386: don't return err in wait.Poll on net.DialTimeout err; tweak time intervals

- README.md
- manifests/010-prometheus-rules.yaml
- manifests/03-rbac-imageconfig-role-binding.yaml
- manifests/03-rbac-imageconfig-role.yaml
- pkg/stub/config.go
- pkg/stub/handler.go
- pkg/stub/imagestreams.go
- pkg/stub/templates.go
Fixes https://github.com/openshift/cluster-samples-operator/issues/385
> Bug 2002368: acccount for image api returning invalid on imagestream create based on allowed/blocked registry settings

- assets/operator/okd-x86_64/ruby/imagestreams/ruby-centos.json
- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
cherry pick failed ... example https://github.com/openshift/cluster-samples-operator/pull/380#issuecomment-914382309
ultimately want to get this back to 4.7 .... see https://github.com/openshift/cluster-samples-operator/issues/385#issuecomment-914379957
/assign @dperaza4dustbit
more tech debt I was still carrying prior to hand off
NOTE: confirmed with @jottofar that the install feature of using an annotation to have CVO delete a given item it manages is not getting backported to 4.7, so we just have to remove the imagestream like we did in 4.8.
> Bug 2001977: delete hello-openshift in payload imagestream

- manifests/07-clusteroperator.yaml
- pkg/operatorstatus/operatorstatus.go
The must-gather tool is collecting imagestreams under the openshift
namespace but it is not collecting templates. Being more prescriptive
on the groups we want to collect for sample related objects.
> Bug 2007757: Including Template in must-gather related objects.

- README.md
- manifests/010-prometheus-rules.yaml
- manifests/03-rbac-imageconfig-role-binding.yaml
- manifests/03-rbac-imageconfig-role.yaml
- pkg/stub/config.go
- pkg/stub/handler.go
- pkg/stub/imagestreams.go
- pkg/stub/templates.go
merge conflicts and multiple PRs https://github.com/openshift/cluster-samples-operator/pull/394 https://github.com/openshift/cluster-samples-operator/pull/397 required to fix in 4.10, so a manual cherry pick vs. using the cherry-pick bot is required for this one
> Bug 2009722: acccount for image api returning invalid on imagestream create based on allowed/blocked registry settings

- assets/operator/ocp-aarch64/cakephp/templates/cakephp-mysql-persistent.json
- assets/operator/ocp-ppc64le/cakephp/templates/cakephp-mysql-persistent.json
- assets/operator/ocp-s390x/cakephp/templates/cakephp-mysql-persistent.json
- assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-persistent.json
- assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-persistent.json
I have already submitted PR for cakeph-ex: https://github.com/sclorg/cakephp-ex/pull/131 and for openshift library: https://github.com/openshift/library/pull/306. Fixing directly hear without synching so we can target this issue only for back porting to 4.10 
Signed-off-by: David Peraza <dperaza@redhat.com>
> Bug 2064610: Remove duplicate v1 from cakephp-mysql templates

- pkg/stub/interfaces.go
Adding an override in the getter methods to make sure the
group is included in our templates and imagestream when they
are created
Signed-off-by: David Peraza <dperaza@redhat.com>
> Jira SO-19: Make sure template and imagestream api version is groupified

- manifests/06-operator-ibm-cloud-managed.yaml
- manifests/06-operator.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
"objectRef": "openshift-cluster-samples-operator/pods/",
"pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": runAsNonRoot != true (pod or containers \"cluster-samples-operator\", \"cluster-samples-operator-watch\" must set securityContext.runAsNonRoot=true)"
}
```
/cc @stlaz
> AUTH-133: manifests/deployment: comply to restricted pod security level

- assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
- assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
- assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
- assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
- assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-base-centos.json
re: https://github.com/openshift/jenkins/pull/1455
/assign @coreydaley 
@openshift/openshift-team-build-api FYI
this is the last step in the "replace ART interactions for getting jenkins image changes into openshift"
/label px-approved
/label qe-approved
/label docs-approved
> update jenkins CPaaS image refs prior to 4.11 GA

- manifests/06-servicemonitor.yaml
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md
> Add client certificate and key to service monitor

- assets/operator/ocp-aarch64/golang/imagestreams/golang-rhel-aarch64.json
- assets/operator/ocp-ppc64le/golang/imagestreams/golang-rhel.json
- assets/operator/ocp-s390x/golang/imagestreams/golang-rhel.json
- assets/operator/ocp-x86_64/golang/imagestreams/golang-rhel.json
- assets/operator/okd-x86_64/golang/imagestreams/golang-centos.json
This is a backport of https://github.com/sclorg/golang-container/pull/45 and the resulting https://github.com/openshift/library/commit/79279a759b7d7394ffbda2d250551e58bd67e44f for 4.11.
/cc @fbm3307
> [release-4.11] OCPBUGS-2092: Use X.Y floating tags for golang

- manifests/08-openshift-imagestreams.yaml
With support landing for importing manifestlists in imagestreams (https://issues.redhat.com/browse/IR-192), making these import the manifestlist by default will help when clusters are installed with the manifestlisted multi release payload and compute nodes of different architectures are added. This will help the CI nightly test suites run without errors on a cluster with multi arch compute nodes and also enable commands like oc debug and must-gather to run on these nodes.
> Change importMode to preserveOriginal for Openshift imagestreams

- pkg/stub/handler.go
- pkg/stub/handler_test.go
This is a fix for the ocpbug855
Signed-off-by: Feny Mehta <fbm3307@gmail.com>
> OCPBUGS-855: When setting allowedRegistries urls the openshift-samples operator is degraded

- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
The network tools image is used by certain tests in origin and the way that is done today [1] is by spinning up a pod with the CVO image and getting the network-tools image spec from inside the pod. This is not desirable and also doesn't work today when these tests run on a cluster with multi arch compute nodes.
This PR adds the network tools imagestreams so these tests can be changed to use the imagestream rather than inferring it through creating a pod today.
[1] https://github.com/openshift/origin/blob/master/test/extended/util/release.go#L32
> OCPBUGS-10910: Add network tools imagestreams

- manifests/08-openshift-imagestreams.yaml
- manifests/image-references
4.13 doesn't look right at this point
added here https://github.com/openshift/cluster-samples-operator/pull/495
> Use latest tag for network-tools imagestream

- assets/operator/okd-x86_64/mariadb/imagestreams/mariadb-centos.json
- assets/operator/okd-x86_64/ruby/imagestreams/ruby-centos.json
OKD tests are currently broken due to imagestream samples introduced in the recent sync containing invalid image import URLs.
This PR contains changes from:
- https://github.com/sclorg/mariadb-container/pull/220
- https://github.com/sclorg/s2i-ruby-container/pull/509
> SO-119: Fix mariadb import url in OKD

- manifests/06-operator-ibm-cloud-managed.yaml
- manifests/06-operator.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

- Dockerfile.okd
Hi team, 
OKD-SCOS for release 4.16 isn't building. Please help us update what is needed. 
Thank you
> OCPBUGS-26992: Align builder and base for Dockerfile.okd with Dockerfile

- library-sync.sh
This updates the `library-sync.sh` script to only update the imagestreams and templates of the supported samples.
This should ease the release process so that we (or any future maintainer) doesn't have to remember to manually go through the changes brought in from openshift and remove any changes to the unsupported samples.
> NO-ISSUE: Only pick up the changes from the supported imagestreams and templates in library-sync.sh.

- library-sync.sh
Improve the handling of changes in the unsupported samples so that no traces are left behind even when files were renamed or moved to a different location.
> OCPBUGS-38994: Fix library-sync.sh to handle renames in unsupported samples

- Dockerfile.okd
base and builder images need to be updated to avoid build failures.
> OKD-225: update okd dockerfile builder and base images

- assets/operator/ocp-aarch64/rails/templates/rails-pgsql-persistent.json
- assets/operator/ocp-aarch64/rails/templates/rails-postgresql-example.json
- assets/operator/ocp-ppc64le/rails/templates/rails-pgsql-persistent.json
- assets/operator/ocp-ppc64le/rails/templates/rails-postgresql-example.json
- assets/operator/ocp-s390x/rails/templates/rails-pgsql-persistent.json
- assets/operator/ocp-s390x/rails/templates/rails-postgresql-example.json
- assets/operator/ocp-x86_64/rails/templates/rails-pgsql-persistent.json
- assets/operator/ocp-x86_64/rails/templates/rails-postgresql-example.json
- assets/operator/okd-x86_64/rails/templates/rails-pgsql-persistent.json
- assets/operator/okd-x86_64/rails/templates/rails-postgresql-example.json
Fix the rails template before the upstream accepts our PR (https://github.com/sclorg/rails-ex/pull/178).
> OCPBUGS-42265: Fix the rails template before the upstream accepts or PR

- assets/operator/okd-x86_64/mariadb/imagestreams/mariadb-centos.json
- assets/operator/okd-x86_64/mysql/imagestreams/mysql-centos.json
- assets/operator/okd-x86_64/perl/imagestreams/perl-centos.json
- assets/operator/okd-x86_64/redis/imagestreams/redis-centos.json
Remove all references to the EOL CentOS 7 images that have been removed, update the redis image to a  scl.org c9s one, as the CentOS 7 one was the only one available
> OKD-225: remove only the EOL CentOS 7 images

- assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-example.json
- assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-persistent.json
- assets/operator/okd-x86_64/dancer/templates/dancer-mysql-example.json
- assets/operator/okd-x86_64/dancer/templates/dancer-mysql-persistent.json
- assets/operator/okd-x86_64/mariadb/imagestreams/mariadb-centos.json
- assets/operator/okd-x86_64/mariadb/templates/mariadb-ephemeral.json
- assets/operator/okd-x86_64/mariadb/templates/mariadb-persistent.json
- assets/operator/okd-x86_64/mysql/imagestreams/mysql-centos.json
- assets/operator/okd-x86_64/mysql/templates/mysql-ephemeral.json
- assets/operator/okd-x86_64/mysql/templates/mysql-persistent.json
- assets/operator/okd-x86_64/openliberty/imagestreams/openliberty.json
- assets/operator/okd-x86_64/postgresql/imagestreams/postgresql-centos.json
- assets/operator/okd-x86_64/postgresql/templates/postgresql-ephemeral.json
- assets/operator/okd-x86_64/redis/imagestreams/redis-centos.json
- assets/operator/okd-x86_64/redis/templates/redis-ephemeral.json
- assets/operator/okd-x86_64/redis/templates/redis-persistent.json
It turns out that there is a test for particular samples being imported into the imagestreams
https://github.com/openshift/origin/blob/master/test/extended/util/framework.go#L315 is the list. so lets add back mysql even though it is unsupported
> OKD-225: Add back mysql samples

- library-sync.sh
This changes `library-sync.sh` such that by default, it only updates the supported samples in OCP for all architectures.
If the `--okd` parameter is supplied to the script, all samples in OKD are updated (there are no unsupported samples in OKD).
> SO-137: Support updating the library separately for OKD and for OCP.

- assets/operator/okd-x86_64/jenkins/templates/jenkins-ephemeral-monitored.json
- assets/operator/okd-x86_64/jenkins/templates/jenkins-ephemeral.json
- assets/operator/okd-x86_64/jenkins/templates/jenkins-persistent-monitored.json
- assets/operator/okd-x86_64/jenkins/templates/jenkins-persistent.json
- assets/operator/okd-x86_64/openliberty/imagestreams/openliberty.json
- assets/operator/okd-x86_64/rails/templates/rails-pgsql-persistent.json
- assets/operator/okd-x86_64/rails/templates/rails-postgresql-example.json
Syncing the latest samples from the library to OKD.
Created using https://github.com/metlos/trigger-test-samples-build
> SO-142: Periodic sync of OKD samples

- Makefile
- pkg/stub/handler.go
- pkg/stub/handler_test.go
Testing the removal of registry.access.redhat.com on redHatRegistriesFound and redHatRegistriesDomainFound functions
The objective of this is to see if the tests actually passes with the removal of this registry as the imagestreams should be able to be created even if registry.access.redhat.com is not on the registrySources.allowedRegistries of the image.config/cluster CR
> OCPBUGS-30313: Removing reference of registry.access.redhat.com

- pkg/stub/handler.go
It seems that the error appears when iterating with some maps that are being readed on the createSamples func.
Testing if putting a lock on the createSamples func avoids this type of situantion without affecting the performance of the component
~~~
fatal error: concurrent map iteration and map write
goroutine 228 [running]:
[github.com/openshift/cluster-samples-operator/pkg/stub.(*Handler).createSamples](https://github.com/openshift/cluster-samples-operator/pkg/stub.(*Handler).createSamples)(0xc0005b26e0, 0xc000bf0200, 0x0, 0x0, 0xc000217740, 0xc00104ffb0)
/go/src/[github.com/openshift/cluster-samples-operator/pkg/stub/handler.go:1167](https://github.com/openshift/cluster-samples-operator/pkg/stub/handler.go:1167) +0xc5
[github.com/openshift/cluster-samples-operator/pkg/stub.(*Handler).Han …
> OCPBUGS-45049: Adding mutex to func createSamples on handler.go

- go.mod
- go.sum
- vendor/golang.org/x/oauth2/LICENSE
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/pkce.go
- vendor/golang.org/x/oauth2/token.go
- vendor/modules.txt
This also bumps go to version 1.23 which shouldn't be an issue as the base image being used on master is rhel-9-golang-1.23-openshift-4.19.
Steps executed: 
$ go get -u golang.org/x/oauth2@v0.27.0
$ go mod tidy
$ go mod vendor
> OCPBUGS-52346: bump x/oauth2 to version 0.27.0

- README.md
README.md - the relevant references to master have been changed to main
> OCPBUGS-52379: relevant references to master renamed in README.md

- pkg/stub/handler.go
Reverts https://github.com/openshift/cluster-samples-operator/pull/601
Samples operator is the only one that is failing the nightly now and we are running out of ideas as to what could be the cause for this. We are reverting both https://github.com/openshift/cluster-samples-operator/pull/602 and https://github.com/openshift/cluster-samples-operator/pull/601 and see if that will make a difference with the official payload run. If proven unrelated, please unrevert this revert and have the change reintroduced to main.
> OCPBUGS-52848: Revert "OCPBUGS-45049: Adding mutex to func createSamples on handler.go"

- go.mod
- go.sum
- vendor/golang.org/x/oauth2/LICENSE
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/pkce.go
- vendor/golang.org/x/oauth2/token.go
- vendor/modules.txt
Reverts https://github.com/openshift/cluster-samples-operator/pull/602
Samples operator is the only one that is failing the nightly now and we are running out of ideas as to what could be the cause for this. We are reverting both https://github.com/openshift/cluster-samples-operator/pull/602 and https://github.com/openshift/cluster-samples-operator/pull/601 and see if that will make a difference with the official payload run. If proven unrelated, please unrevert this revert and have the change reintroduced to main.
> OCPBUGS-52848: Revert "OCPBUGS-52346: bump x/oauth2 to version 0.27.0"

- pkg/stub/handler.go
Reverts openshift/cluster-samples-operator#607
This proved not to be the issue.
> OCPBUGS-52848: Unrevert the revert "OCPBUGS-45049: Adding mutex to func createSamples on handler.go"

- README.md
There are 2 broken hyperlinks in the README.md file for the Cluster Samples operator.
Basically, the 2 links have been broken for several releases and renaming master to main won't have fixed them.
Also, the value "Failing" for the "CVO Cluster Operator Status" needs to be changed to "Degraded" to match the online documentation and the code
For further details, please see the README.md changes and the Jira OCPBUGS-54149
> OCPBUGS-54149: Updates to README.md

- pkg/stub/handler_test.go
Unit tests currently fail on a Macbook Pro with an Arm chip:
1. clone the CSO https://github.com/openshift/cluster-samples-operator
2. cd ./openshift/cluster-samples-operator/pkg/stub     
3. run the unit tests in a Macbook Termninal on a Macbook Pro M3 with an Arm chip and grep for failures:
go test . | grep FAIL:
--- FAIL: TestManagementState (0.00s)
--- FAIL: TestProcessed (0.00s)
--- FAIL: TestImageStreamEvent (0.00s)
--- FAIL: TestImageStreamErrorRetry (0.00s)
--- FAIL: TestTemplateEvent (0.00s)
--- FAIL: TestImageStreamCreateErrorDegradedReason (0.00s)
--- FAIL: TestImageGetError (0.00s)
--- FAIL: TestImageUpdateError (0.00s)
--- FAIL: TestTemplateGetError (0.00s)
--- FAIL: TestTemplateUpsertError (0.00s)
--- FAIL: TestBadTopDirList (0.00s)
--- FAIL: TestBadSubDirList (0.00s)
This …
> OCPBUGS-54349: cluster-samples-operator - fix failing unit tests MacBook (ARM chip)

- manifests/08-openshift-imagestreams.yaml
This hello-openshift ImageStream  is removed in ocp 4.8 within https://github.com/openshift/cluster-samples-operator/pull/380
And now the OCP 4.18 has no longer need this YAML anymore, remove the redundant YAML
> NO-JIRA: cleanup hello-openshift yaml 

- Dockerfile.okd
OCPBUGS-60179: Bump Kubernetes Version to v0.33.3 - update Dockerfile.okd
> OCPBUGS-60179: Bump Kubernetes Version to v0.33.3 - update Dockerfile.okd
